### ISSUE TITLE
Thread not working with build

### ISSUE THREAD

**Issue by JRohrback13** [trevinofernando/ADLTS#1]
Upon compiling ADLTS_V1, an error is thrown. The error code is "undefined reference to symbol 'pthread_create@@GLIBC_2.4'."

**Comment by trevinofernando** [comment]
This website have some options that we can try: https://www.raspberrypi.org/forums/viewtopic.php?t=104926

**Comment by JRohrback13** [comment]
Fixed issue by including -pthread in linker options
